{{- if .Values.devicePlugin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hami-vgpu.device-plugin" . }}-monitor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: hami-scheduler
    {{- include "hami-vgpu.labels" . | nindent 4 }}
    {{- if .Values.scheduler.service.labels }}
    {{ toYaml .Values.scheduler.service.labels | indent 4 }}
    {{- end }}
  {{- if .Values.scheduler.service.annotations }}
  annotations: {{ toYaml .Values.scheduler.service.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/component: hami-device-plugin
  type: ClusterIP
  ports:
    - name: monitorport
      port: {{ .Values.devicePlugin.service.httpPort }}
      targetPort: 9394
{{- end }}