{{- if .Values.scheduler.enabled }}
{{- if .Values.scheduler.kubeScheduler.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hami-vgpu.scheduler" . }}-newversion
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: hami-scheduler
    {{- include "hami-vgpu.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if gt (.Values.scheduler.kubeScheduler.imageTag | substr 3 5| atoi) 25}}
    apiVersion: kubescheduler.config.k8s.io/v1
    {{- else }}
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    {{- end }}
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: {{ .Values.scheduler.leaderElect }}
      resourceName: {{ .Values.schedulerName }}
    profiles:
    - schedulerName: {{ .Values.schedulerName }}
      {{- if .Values.scheduler.kubeScheduler.plugins.enabled }}
      plugins:
        filter:
          enabled:
            - name: hwameistor-scheduler-plugin
        reserve:
          enabled:
            - name: hwameistor-scheduler-plugin
        score:
          enabled:
            - name: hwameistor-scheduler-plugin
              weight: 10
      {{- end }}
    extenders:
    - urlPrefix: "https://127.0.0.1:443"
      filterVerb: filter
      bindVerb: bind
      nodeCacheCapable: true
      weight: 1
      httpTimeout: 30s
      enableHTTPS: true
      tlsConfig:
        insecure: true
      managedResources:
      {{- range ( split ";" $.Values.resourceName ) }}
      - name: {{ . }}
        ignoredByScheduler: true
      {{- end }}
      - name: {{ .Values.resourceMem }}
        ignoredByScheduler: true
      - name: {{ .Values.resourceCores }}
        ignoredByScheduler: true
      - name: {{ .Values.resourceMemPercentage }}
        ignoredByScheduler: true
      - name: {{ .Values.resourcePriority }}
        ignoredByScheduler: true
      - name: {{ .Values.mluResourceName }}
        ignoredByScheduler: true
      - name: {{ .Values.dcuResourceName }}
        ignoredByScheduler: true
      - name: {{ .Values.dcuResourceMem }}
        ignoredByScheduler: true
      - name: {{ .Values.dcuResourceCores }}
        ignoredByScheduler: true
      - name: {{ .Values.iluvatarResourceName }}
        ignoredByScheduler: true
      - name: {{ .Values.ascendResourceMem }}
        ignoredByScheduler: true
      - name: {{ .Values.ascendResourceName }}
        ignoredByScheduler: true
{{- end }}
{{- end }}
